/***************************************************************************
 EventInfo Package
 -----------------------------------------
 Copyright (C) 2000 by ATLAS Collaboration
 ***************************************************************************/

//<doc><file>	$Id: TriggerInfo.h,v 1.1.1.1 2007/04/25 11:46:57 zoujh Exp $
//<version>	$Name: HltDataTypes-01-01-03 $

#ifndef EVENTINFO_TRIGGERINFO_H
# define EVENTINFO_TRIGGERINFO_H 1

//<<<<<< INCLUDES                                                       >>>>>>

#include <vector>
#include <string>

//<<<<<< PUBLIC DEFINES                                                 >>>>>>
//<<<<<< PUBLIC CONSTANTS                                               >>>>>>
//<<<<<< PUBLIC TYPES                                                   >>>>>>
//<<<<<< PUBLIC VARIABLES                                               >>>>>>
//<<<<<< PUBLIC FUNCTIONS                                               >>>>>>
//<<<<<< CLASS DECLARATIONS                                             >>>>>>

/**
 **  class TriggerInfo
 **
 **  This class contains trigger related information:
 **
 **    extendedLevel1ID - The extended LVL1 ID [3] formed by the 24-bit
 **                       L1ID generated in the TTCrx and the 8-bit
 **                       ECRID ** implemented in the ROD.
 **
 **    level1TriggerType - An 8-bit word as generated by the Central
 **                        Trigger Processor and transmitted by the
 **                        TTC system [4]. The ** remaining 24-bits
 **                        are un-used.
 **
 **    level2TriggerInfo - Summary information regarding the event. The
 **                        element is one 32-bit integer. The possible
 **                        values ** that this element may take are
 **                        still to be defined.
 **
 **    eventFilterInfo - Summary information regarding the event. The
 **                      element is four 32-bit integers in size. The
 **                      possible values ** that this element may take
 **                      are still to be defined.
 **  
 **/
class TriggerInfo {
public:

    // public typedefs:
    typedef unsigned int number_type;

    TriggerInfo();
    TriggerInfo(number_type extendedLevel1ID,
		number_type level1TriggerType,
		number_type level2TriggerInfo,
		const std::vector<number_type>& eventFilterInfo);
    virtual ~TriggerInfo();


    /// Access to info
    number_type extendedLevel1ID 	() const;
    number_type level1TriggerType	() const;
    number_type level2TriggerInfo	() const;
    const std::vector<number_type>& eventFilterInfo () const;

private:
    number_type               m_extendedLevel1ID;
    number_type               m_level1TriggerType;
    number_type               m_level2TriggerInfo;
    std::vector<number_type>  m_eventFilterInfo;
};


//<<<<<< INLINE PUBLIC FUNCTIONS                                        >>>>>>
//<<<<<< INLINE MEMBER FUNCTIONS                                        >>>>>>

#endif // EVENTINFO_TRIGGERINFO_H
