/* Random/defs.h.  Generated by configure.  */
/* Random/defs.h.in.  Generated from configure.in by autoheader.  */

#ifndef RANDOM_DEFS_H
#define RANDOM_DEFS_H

/* Define to 1 if you have the `drand48' function. */
#define HAVE_DRAND48 1

/* Name of package */
#ifndef PACKAGE
#define PACKAGE "Random"
#endif

/* Define to the address where bug reports for this package should be sent. */
#ifndef PACKAGE_BUGREPORT
#define PACKAGE_BUGREPORT "http://savannah.cern.ch/projects/clhep/"
#endif

/* Define to the full name of this package. */
#ifndef PACKAGE_NAME
#define PACKAGE_NAME "CLHEP Random"
#endif

/* Define to the full name and version of this package. */
#ifndef PACKAGE_STRING
#define PACKAGE_STRING "CLHEP Random 2.0.4.5"
#endif

/* Define to the one symbol short name of this package. */
#ifndef PACKAGE_TARNAME
#define PACKAGE_TARNAME "Random"
#endif

/* Define to the version of this package. */
#ifndef PACKAGE_VERSION
#define PACKAGE_VERSION "2.0.4.5"
#endif

/* Version number of package */
#ifndef VERSION
#define VERSION "2.0.4.5"
#endif

#endif  // RANDOM_DEFS_H
