/* This is file is automatically generated */
#define BUILD_ARCH "linuxx8664gcc"
#define BUILD_NODE "Linux lxbuild101.cern.ch 2.6.32-131.6.1.el6.x86_64 #1 SMP Wed Jul 13 09:00:34 CEST 2011 x86_64 x86_64 x86_64 GNU/Linux" 
#define COMPILER "/afs/cern.ch/sw/lcg/contrib/gcc/4.6.3/x86_64-slc6/bin/g++" 
#define COMPILERVERS "gcc463"
#define MAKESHAREDLIB  "cd $BuildDir ; g++ -c $Opt -pipe -m64 -Wshadow -Wall -W -Woverloaded-virtual -fPIC -DG__MAXSTRUCT=36000 -DG__MAXTYPEDEF=36000 -DG__LONGLINE=4096 -pthread $IncludePath $SourceFiles ; g++ $ObjectFiles -shared -Wl,-soname,$LibName.so -m64 -O2  -Wl,--no-undefined -Wl,--as-needed $LinkedLibs -o $SharedLib"
#define MAKEEXE "cd $BuildDir ; g++ -c  -pipe -m64 -Wshadow -Wall -W -Woverloaded-virtual -fPIC -DG__MAXSTRUCT=36000 -DG__MAXTYPEDEF=36000 -DG__LONGLINE=4096 -pthread $IncludePath $SourceFiles; g++ $ObjectFiles -m64 -O2  -Wl,--no-undefined -Wl,--as-needed -o $ExeName $LinkedLibs -lm -ldl  -pthread   -rdynamic"
#define CXXOPT "-O2"
#define CXXDEBUG "-g"
#define ROOTBUILD ""
#define LINKEDLIBS "-L$ROOTSYS/lib -lCore -lCint -lRint "
#define INCLUDEPATH "-I$ROOTSYS/include"
#define OBJEXT "o" 
#define SOEXT "so" 
