/* RandomObjects/defs.h.  Generated by configure.  */
/* RandomObjects/defs.h.in.  Generated from configure.in by autoheader.  */

#ifndef RANDOMOBJECTS_DEFS_H
#define RANDOMOBJECTS_DEFS_H

/* Name of package */
#ifndef PACKAGE
#define PACKAGE "RandomObjects"
#endif

/* Define to the address where bug reports for this package should be sent. */
#ifndef PACKAGE_BUGREPORT
#define PACKAGE_BUGREPORT "http://savannah.cern.ch/projects/clhep/"
#endif

/* Define to the full name of this package. */
#ifndef PACKAGE_NAME
#define PACKAGE_NAME "CLHEP RandomObjects"
#endif

/* Define to the full name and version of this package. */
#ifndef PACKAGE_STRING
#define PACKAGE_STRING "CLHEP RandomObjects 2.0.4.5"
#endif

/* Define to the one symbol short name of this package. */
#ifndef PACKAGE_TARNAME
#define PACKAGE_TARNAME "RandomObjects"
#endif

/* Define to the version of this package. */
#ifndef PACKAGE_VERSION
#define PACKAGE_VERSION "2.0.4.5"
#endif

/* Version number of package */
#ifndef VERSION
#define VERSION "2.0.4.5"
#endif

#endif  // RANDOMOBJECTS_DEFS_H
